# Generated by Django 5.0.3 on 2024-03-29 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_remove_feedback_apikey'),
        ('users', '0003_alter_user_managers_rename_apikey_apikey_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='api key'),
        ),
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
